(() => {
'use strict';
const VERSION='2.0.7', STORAGE_KEY='hooptrack-v1';
const basePeriod=()=>({ftMade:0,ftMiss:0,twoMade:0,twoMiss:0,threeMade:0,threeMiss:0,assists:0,rebounds:0,steals:0,blocks:0,turnovers:0,fouls:0});
const initial={games:[],activeGameId:null,playerName:'',seasonName:'',leagueName:'',teamName:'',settings:{theme:'system',haptics:true,wakeLock:true,playTime:false},filters:{dashboardSeason:'',dashboardLeague:'',season:'',seasonLeague:'',historySeason:'',historyLeague:'',historySort:'newest',favoritesOnly:false,historySearch:''}};
const clone=o=>JSON.parse(JSON.stringify(o));
let state=loadState(), wakeLock=null, timerHandle=null, currentView='home', cardPhoto=null, cardBlob=null;
const $=id=>document.getElementById(id), $$=sel=>[...document.querySelectorAll(sel)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const id=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2);
function normalizePeriod(p={}){const n=basePeriod(); if('ft' in p){n.ftMade=+p.ft||0;n.twoMade=+p.two||0;n.threeMade=+p.three||0;} for(const k of Object.keys(n)) if(k in p)n[k]=+p[k]||0; return n}
function normalizeGame(g){let periods={}; if(g.periods) for(const [k,v] of Object.entries(g.periods)) periods[k]=normalizePeriod(v); else if(g.quarters) for(const [k,v] of Object.entries(g.quarters)) periods['Q'+k]=normalizePeriod(v); ['Q1','Q2','Q3','Q4'].forEach(k=>periods[k]??=basePeriod()); return {...g,seasonName:g.seasonName||'Unassigned',leagueName:g.leagueName||'Unassigned',teamName:g.teamName||'Unassigned',notes:g.notes||'',favorite:!!g.favorite,teamScore:g.teamScore===''||g.teamScore==null?'':Math.max(0,+g.teamScore||0),opponentScore:g.opponentScore===''||g.opponentScore==null?'':Math.max(0,+g.opponentScore||0),periods,activePeriod:g.activePeriod||(g.activeQuarter?'Q'+g.activeQuarter:'Q1'),events:Array.isArray(g.events)?g.events.map(e=>({...e,period:e.period||(e.quarter?'Q'+e.quarter:'Q1'),stat:mapLegacyStat(e.stat)})):[],achievements:g.achievements||{},playTimeMs:+g.playTimeMs||0,isPlaying:!!g.isPlaying,playStartedAt:g.playStartedAt||null};}
function mapLegacyStat(s){return ({ft:'ftMade',two:'twoMade',three:'threeMade'})[s]||s}
function loadState(){try{const raw=localStorage.getItem(STORAGE_KEY); if(!raw)return clone(initial); const p=JSON.parse(raw); const merged={...clone(initial),...p,settings:{...initial.settings,...p.settings},filters:{...initial.filters,...p.filters},games:(p.games||[]).map(normalizeGame)}; if(!merged.playerName&&merged.games.length)merged.playerName=[...merged.games].reverse().find(g=>g.playerName)?.playerName||''; if(!merged.seasonName)merged.seasonName=[...merged.games].reverse().find(g=>g.seasonName)?.seasonName||''; if(!merged.leagueName)merged.leagueName=[...merged.games].reverse().find(g=>g.leagueName)?.leagueName||''; if(!merged.teamName)merged.teamName=[...merged.games].reverse().find(g=>g.teamName)?.teamName||''; return merged}catch(e){return clone(initial)}}
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); const activeGame=()=>state.games.find(g=>g.id===state.activeGameId)||null;
function fmtDate(s){if(!s)return'';const [y,m,d]=s.split('-').map(Number);return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(y,m-1,d))}
function periodPoints(p){return p.ftMade+p.twoMade*2+p.threeMade*3}
function totals(g){const t=basePeriod();for(const p of Object.values(g.periods||{}))for(const k in t)t[k]+=+p[k]||0; const fgMade=t.twoMade+t.threeMade,fgAtt=fgMade+t.twoMiss+t.threeMiss,threeAtt=t.threeMade+t.threeMiss,ftAtt=t.ftMade+t.ftMiss; return {...t,points:t.ftMade+t.twoMade*2+t.threeMade*3,fgMade,fgAtt,threeAtt,ftAtt,fgPct:pct(fgMade,fgAtt),twoPct:pct(t.twoMade,t.twoMade+t.twoMiss),threePct:pct(t.threeMade,threeAtt),ftPct:pct(t.ftMade,ftAtt),efgPct:fgAtt?((fgMade+.5*t.threeMade)/fgAtt*100):0,minutes:playMinutes(g)}}
const pct=(m,a)=>a?m/a*100:0; const f1=n=>(+n||0).toFixed(1); const fp=n=>`${f1(n)}%`;
function hasFinalScore(g){return g.teamScore!==''&&g.teamScore!=null&&g.opponentScore!==''&&g.opponentScore!=null}
function finalScoreText(g){return hasFinalScore(g)?`${g.teamName||'Team'} ${g.teamScore}, ${g.opponent||'Opponent'} ${g.opponentScore}`:''}
function resultText(g){if(!hasFinalScore(g))return'';return +g.teamScore>+g.opponentScore?'Win':+g.teamScore<+g.opponentScore?'Loss':'Tie'}
function playMilliseconds(g){return (g.playTimeMs||0)+(g.isPlaying&&g.playStartedAt?Date.now()-g.playStartedAt:0)} function playMinutes(g){return playMilliseconds(g)/60000} function timeText(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60);return `${m}:${String(s%60).padStart(2,'0')}`}
function achievementList(g){const t=totals(g),out=[],dd=[t.points,t.assists,t.rebounds,t.steals,t.blocks].filter(v=>v>=10).length;if(dd>=3)out.push(['Triple-Double','purple','🏆']);else if(dd>=2)out.push(['Double-Double','gold','★']);if(t.points>=30)out.push(['30 Point Game','gold','🔥']);else if(t.points>=20)out.push(['20 Point Game','gold','🔥']);if(t.threeMade>=5)out.push(['5 Threes','green','🎯']);if(t.blocks>=5)out.push(['5 Blocks','green','🧱']);if(t.steals>=5)out.push(['5 Steals','green','🖐']);if(t.assists>=10)out.push(['10 Assists','green','🎁']);if(t.rebounds>=10)out.push(['10 Rebounds','green','💪']);return out}
function achievementBadges(g){return achievementList(g).map(([n,c,i])=>`<span class="badge ${c}">${i} ${esc(n)}</span>`).join('')}
function checkReward(g){const now=achievementList(g).map(x=>x[0]);g.achievements ||= {};for(const name of now){if(!g.achievements[name]){g.achievements[name]=true;return name}}return null}
function showReward(name){const g=activeGame();if(!g)return;$('rewardTitle').textContent=name;$('rewardMessage').textContent=`${g.playerName} earned ${name}.`;$('rewardIcon').textContent=name==='Triple-Double'?'🏆':name.includes('Point')?'🔥':'★';$('rewardDialog').showModal();vibrate([60,40,80])}
function vibrate(pattern=18){if(state.settings.haptics&&navigator.vibrate)navigator.vibrate(pattern)}
function applyTheme(){let t=state.settings.theme;if(t==='system')t=matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';document.documentElement.dataset.theme=t;$('themeSelect').value=state.settings.theme;document.querySelector('meta[name="theme-color"]').content=t==='light'?'#f4f7fb':'#07111f'}
function unique(field){return [...new Set(state.games.map(g=>g[field]).filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function fillSelect(el,vals,selected,allLabel){el.innerHTML=`<option value="">${allLabel}</option>`+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');el.value=vals.includes(selected)?selected:''}
function completed(games){return games.filter(g=>g.endedAt)} function agg(games){const gs=completed(games),sum={points:0,assists:0,rebounds:0,steals:0,blocks:0,turnovers:0,fouls:0,fgMade:0,fgAtt:0,threeMade:0,threeAtt:0,ftMade:0,ftAtt:0};for(const g of gs){const t=totals(g);for(const k in sum)sum[k]+=t[k]||0}return{games:gs,sum,avg:k=>gs.length?sum[k]/gs.length:0,fgPct:pct(sum.fgMade,sum.fgAtt),threePct:pct(sum.threeMade,sum.threeAtt),ftPct:pct(sum.ftMade,sum.ftAtt)}}
function statCard(label,val){return `<div class="stat-card"><span>${label}</span><strong>${val}</strong></div>`}
function shootingCards(t){return `<div class="shooting-summary"><div><span>FG</span><strong>${t.fgMade}/${t.fgAtt}</strong><em>${fp(t.fgPct)}</em></div><div><span>2PT</span><strong>${t.twoMade}/${t.twoMade+t.twoMiss}</strong><em>${fp(t.twoPct)}</em></div><div><span>3PT</span><strong>${t.threeMade}/${t.threeAtt}</strong><em>${fp(t.threePct)}</em></div><div><span>FT</span><strong>${t.ftMade}/${t.ftAtt}</strong><em>${fp(t.ftPct)}</em></div><div><span>eFG</span><strong>${fp(t.efgPct)}</strong><em>effective</em></div></div>`}
function setView(v){if(v==='game'&&!activeGame()){const latest=[...state.games].reverse().find(g=>!g.endedAt)||state.games.at(-1);if(latest)state.activeGameId=latest.id;else v='home'} currentView=v;$$('.view').forEach(x=>x.classList.remove('active'));$(`${v}View`).classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));renderAll(); if(v==='game')requestWake();else releaseWake()}
function scopedGames(season,league){return state.games.filter(g=>(!season||g.seasonName===season)&&(!league||g.leagueName===league))}
function renderAll(){renderHeader();renderHome();renderGame();renderSeason();renderHistory();renderCardBuilder();renderSettings()}
function renderHeader(){$('headerContext').textContent=state.playerName?`${state.playerName} • ${state.seasonName||'No season'}`:'One-player basketball tracker'}
function renderHome(){ $('homePlayerName').textContent=state.playerName||'Set player in Settings';$('homeSeasonName').textContent=state.seasonName||'No season';$('homeLeagueName').textContent=state.leagueName||'No league';$('homeTeamName').textContent=state.teamName||'No team';const seasons=unique('seasonName'),leagues=unique('leagueName');fillSelect($('dashboardSeasonFilter'),seasons,state.filters.dashboardSeason,'All seasons');fillSelect($('dashboardLeagueFilter'),leagues,state.filters.dashboardLeague,'All leagues');const gs=scopedGames(state.filters.dashboardSeason,state.filters.dashboardLeague),a=agg(gs);$('scopeLabel').textContent=[state.filters.dashboardSeason,state.filters.dashboardLeague].filter(Boolean).join(' • ')||'All games';$('overviewStats').innerHTML=statCard('Games',a.games.length)+statCard('PPG',f1(a.avg('points')))+statCard('RPG',f1(a.avg('rebounds')))+statCard('APG',f1(a.avg('assists')))+statCard('SPG',f1(a.avg('steals')))+statCard('BPG',f1(a.avg('blocks')));const metrics=[['Points','points'],['Rebounds','rebounds'],['Assists','assists'],['Steals','steals'],['Blocks','blocks']];$('seasonHighs').innerHTML=metrics.map(([l,k])=>{let best=null,val=-1;for(const g of a.games){const n=totals(g)[k];if(n>val){val=n;best=g}}return `<div class="high-item"><span>${l}</span><b>${val<0?0:val}</b></div>`}).join('');const last=a.games.slice().sort((x,y)=>(y.date||'').localeCompare(x.date||'')).slice(0,5),la=agg(last);$('lastFiveStats').innerHTML=statCard('PPG',f1(la.avg('points')))+statCard('RPG',f1(la.avg('rebounds')))+statCard('APG',f1(la.avg('assists')))+statCard('SPG',f1(la.avg('steals')))+statCard('BPG',f1(la.avg('blocks')));$('recentGames').innerHTML=last.slice(0,3).map(gameCard).join('')||'<div class="empty">No completed games yet.</div>';drawTrend(last.slice().reverse(),$('trendMetric').value)}
function gameCard(g,history=false){const t=totals(g),score=finalScoreText(g),result=resultText(g);return `<article class="game-card" data-game-card="${g.id}"><div class="game-card-top"><div>${history?`<label class="check"><input type="checkbox" data-compare="${g.id}"> Compare</label>`:''}<div class="eyebrow">${g.endedAt?'FINAL':'IN PROGRESS'} ${g.favorite?'<span class="favorite-star">★</span>':''}</div><h3>vs ${esc(g.opponent)}</h3><div class="muted small">${fmtDate(g.date)} • ${esc(g.seasonName)} • ${esc(g.leagueName)} • ${esc(g.teamName)}</div>${score?`<div class="score-result">${esc(score)}</div>`:''}<div class="badge-row">${achievementBadges(g)}</div></div><div class="score"><div>${t.points}</div><span class="muted small">PTS</span></div></div><div class="meta-row">${result?`<span class="pill">${result}</span>`:''}<span class="pill">${t.rebounds} REB</span><span class="pill">${t.assists} AST</span><span class="pill">${t.steals} STL</span><span class="pill">${t.blocks} BLK</span><span class="pill">${fp(t.fgPct)} FG</span></div><div class="game-actions"><button class="icon-action" data-view-game="${g.id}" title="View" aria-label="View">◉</button><button class="icon-action" data-share-game="${g.id}" title="Share" aria-label="Share">↗</button><button class="icon-action" data-favorite-game="${g.id}" title="Favorite" aria-label="Favorite">${g.favorite?'★':'☆'}</button><button class="icon-action" data-delete-game="${g.id}" title="Delete" aria-label="Delete">⌫</button></div></article>`}
function drawTrend(games,metric){const c=$('trendCanvas'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||700,h=Math.min(320,Math.max(220,w*.42));c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const style=getComputedStyle(document.documentElement),border=style.getPropertyValue('--border'),muted=style.getPropertyValue('--muted'),accent=style.getPropertyValue('--accent2');ctx.strokeStyle=border;ctx.fillStyle=muted;ctx.font='12px system-ui';for(let i=0;i<4;i++){const y=24+i*(h-60)/3;ctx.beginPath();ctx.moveTo(36,y);ctx.lineTo(w-12,y);ctx.stroke()}if(!games.length){ctx.fillText('No games to chart',40,h/2);return}const vals=games.map(g=>metric==='fgPct'?totals(g).fgPct:totals(g)[metric]),max=Math.max(1,...vals);ctx.strokeStyle=accent;ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{const x=40+(w-60)*(vals.length===1?.5:i/(vals.length-1)),y=24+(h-60)*(1-v/max);i?ctx.lineTo(x,y):ctx.moveTo(x,y);ctx.fillStyle=accent;ctx.fillRect(x-3,y-3,6,6);ctx.fillStyle=muted;ctx.fillText(games[i].opponent.slice(0,8),Math.max(2,x-20),h-12)});ctx.stroke()}
function periodOrder(g){const keys=Object.keys(g.periods);return keys.sort((a,b)=>{const n=x=>x.startsWith('Q')?+x.slice(1):4+(+x.slice(2)||1);return n(a)-n(b)})}
function ensurePeriod(g,p){g.periods[p]??=basePeriod()}
function renderGame(){const g=activeGame();if(!g)return;const t=totals(g);$('gameMeta').textContent=`${fmtDate(g.date)} • ${g.seasonName} • ${g.leagueName}`;$('gameOpponent').textContent=`vs ${g.opponent}`;$('gameSubmeta').textContent=`${g.playerName} • ${g.teamName}`;$('livePoints').textContent=t.points;$('periodBar').innerHTML=periodOrder(g).map(p=>`<button class="period-btn ${p===g.activePeriod?'active':''}" data-period="${p}" type="button">${p}</button>`).join('')+(!g.endedAt?'<button id="addOTBtn" class="period-btn" type="button">+ OT</button>':'');$('liveStats').innerHTML=statCard('PTS',t.points)+statCard('REB',t.rebounds)+statCard('AST',t.assists)+statCard('STL',t.steals)+statCard('BLK',t.blocks)+statCard('TO',t.turnovers)+statCard('PF',t.fouls);$('shootingLine').innerHTML=shootingCards(t);$('btnAssists').textContent=t.assists;$('btnRebounds').textContent=t.rebounds;$('btnSteals').textContent=t.steals;$('btnBlocks').textContent=t.blocks;$('btnTurnovers').textContent=t.turnovers;$('btnFouls').textContent=t.fouls;$('teamScoreInput').value=g.teamScore;$('opponentScoreInput').value=g.opponentScore;$('finalScoreSaved').textContent='Saved';$('gameNotes').value=g.notes;$('gameNotes').disabled=!!g.endedAt;$('periodTableBody').innerHTML=periodOrder(g).map(k=>{const p=g.periods[k],fg=p.twoMade+p.threeMade,fa=fg+p.twoMiss+p.threeMiss;return `<tr><td>${k}</td><td>${periodPoints(p)}</td><td>${fg}/${fa}</td><td>${p.threeMade}/${p.threeMade+p.threeMiss}</td><td>${p.ftMade}/${p.ftMade+p.ftMiss}</td><td>${p.assists}</td><td>${p.rebounds}</td><td>${p.steals}</td><td>${p.blocks}</td><td>${p.turnovers}</td><td>${p.fouls}</td></tr>`}).join('');$('eventLog').innerHTML=g.events.slice().reverse().map(e=>`<div class="event-item"><span class="event-period">${e.period}</span><span>${eventLabel(e.stat)}</span><button class="event-delete" data-delete-event="${e.id}" title="Delete event" aria-label="Delete event">⌫</button></div>`).join('')||'<div class="empty">No events yet.</div>';$('undoBtn').disabled=!!g.endedAt||!g.events.length;$('endGameBtn').classList.toggle('hidden',!!g.endedAt);$('resumeGameBtn').classList.toggle('hidden',!g.endedAt);$('favoriteBtn').textContent=g.favorite?'★ Favorited':'☆ Favorite';$$('[data-stat]').forEach(b=>b.disabled=!!g.endedAt);$('togglePlayBtn').classList.toggle('hidden',!state.settings.playTime);$('playTime').textContent=timeText(playMilliseconds(g));$('playStatus').textContent=!state.settings.playTime?'Playing-time tracking disabled':g.isPlaying?'On court':'On bench';$('togglePlayBtn').textContent=g.isPlaying?'ON BENCH':'IN GAME'}
function eventLabel(s){return({ftMade:'+1 Free throw',ftMiss:'Missed free throw',twoMade:'+2 Field goal',twoMiss:'Missed 2PT',threeMade:'+3 Three-pointer',threeMiss:'Missed 3PT',assists:'Assist',rebounds:'Rebound',steals:'Steal',blocks:'Block',turnovers:'Turnover',fouls:'Personal foul'})[s]||s}
function logStat(stat){const g=activeGame();if(!g||g.endedAt)return;ensurePeriod(g,g.activePeriod);g.periods[g.activePeriod][stat]=(g.periods[g.activePeriod][stat]||0)+1;g.events.push({id:id(),stat,period:g.activePeriod,at:Date.now()});const reward=checkReward(g);save();renderGame();vibrate();if(reward)showReward(reward)}
function deleteEvent(eid){const g=activeGame();if(!g||g.endedAt)return;const i=g.events.findIndex(e=>e.id===eid);if(i<0)return;const e=g.events[i];if(g.periods[e.period]&&g.periods[e.period][e.stat]>0)g.periods[e.period][e.stat]--;g.events.splice(i,1);save();renderGame();vibrate([20,30,20])}
function togglePlaying(){const g=activeGame();if(!g||g.endedAt||!state.settings.playTime)return;if(g.isPlaying){g.playTimeMs+=Date.now()-g.playStartedAt;g.isPlaying=false;g.playStartedAt=null}else{g.isPlaying=true;g.playStartedAt=Date.now()}save();renderGame()}
function readScoreInput(id){const v=$(id).value.trim();return v===''?'':Math.max(0,Math.floor(+v||0))}
function saveFinalScore(){const g=activeGame();if(!g)return;g.teamScore=readScoreInput('teamScoreInput');g.opponentScore=readScoreInput('opponentScoreInput');save();$('finalScoreSaved').textContent='Saved';renderHome();renderHistory()}
async function requestWake(){if(!state.settings.wakeLock||!activeGame()||activeGame().endedAt||!('wakeLock'in navigator))return;try{wakeLock=await navigator.wakeLock.request('screen')}catch{}}
async function releaseWake(){try{await wakeLock?.release()}catch{}wakeLock=null}
function renderSeason(){const seasons=unique('seasonName'),leagues=unique('leagueName');fillSelect($('seasonFilter'),seasons,state.filters.season,'All seasons');fillSelect($('seasonLeagueFilter'),leagues,state.filters.seasonLeague,'All leagues');const gs=scopedGames(state.filters.season,state.filters.seasonLeague),a=agg(gs);$('seasonSummary').innerHTML=statCard('Games',a.games.length)+statCard('PPG',f1(a.avg('points')))+statCard('RPG',f1(a.avg('rebounds')))+statCard('APG',f1(a.avg('assists')))+statCard('FG%',fp(a.fgPct))+statCard('3PT%',fp(a.threePct));const ordered=completed(gs).slice().sort((x,y)=>(y.date||'').localeCompare(x.date||'')),recent=agg(ordered.slice(0,5)),previous=agg(ordered.slice(5,10));$('recentComparison').innerHTML=[['Last 5',recent],['Previous 5',previous]].map(([label,x])=>`<div class="league-card"><h3>${label}</h3><div class="meta-row"><span class="pill">${x.games.length} GP</span><span class="pill">${f1(x.avg('points'))} PPG</span><span class="pill">${f1(x.avg('rebounds'))} RPG</span><span class="pill">${f1(x.avg('assists'))} APG</span><span class="pill">${fp(x.fgPct)} FG</span></div></div>`).join('');const byLeague=unique('leagueName').map(l=>[l,agg(scopedGames(state.filters.season,l))]).filter(([,x])=>x.games.length);$('leagueComparison').innerHTML=byLeague.map(([l,x])=>`<div class="league-card"><h3>${esc(l)}</h3><div class="meta-row"><span class="pill">${x.games.length} GP</span><span class="pill">${f1(x.avg('points'))} PPG</span><span class="pill">${f1(x.avg('rebounds'))} RPG</span><span class="pill">${f1(x.avg('assists'))} APG</span><span class="pill">${fp(x.fgPct)} FG</span></div></div>`).join('')||'<div class="empty">No league data.</div>';const counts={};for(const g of completed(gs))for(const [name] of achievementList(g))counts[name]=(counts[name]||0)+1;$('achievementSummary').innerHTML=Object.entries(counts).map(([n,c])=>`<div class="achievement-card"><h3>${esc(n)}</h3><strong>${c}</strong><div class="muted small">game${c===1?'':'s'}</div></div>`).join('')||'<div class="empty">No achievements yet.</div>'}
function historyGames(){let gs=state.games.filter(g=>(!state.filters.historySeason||g.seasonName===state.filters.historySeason)&&(!state.filters.historyLeague||g.leagueName===state.filters.historyLeague)&&(!state.filters.favoritesOnly||g.favorite));const q=state.filters.historySearch.trim().toLowerCase();if(q)gs=gs.filter(g=>(g.opponent+' '+g.notes+' '+g.teamName).toLowerCase().includes(q));const s=state.filters.historySort;return gs.sort((a,b)=>s==='oldest'?(a.date||'').localeCompare(b.date||''):s==='points'?totals(b).points-totals(a).points:s==='opponent'?a.opponent.localeCompare(b.opponent):(b.date||'').localeCompare(a.date||''))}
function renderHistory(){fillSelect($('historySeasonFilter'),unique('seasonName'),state.filters.historySeason,'All seasons');fillSelect($('historyLeagueFilter'),unique('leagueName'),state.filters.historyLeague,'All leagues');$('historySort').value=state.filters.historySort;$('favoritesOnly').checked=state.filters.favoritesOnly;$('historySearch').value=state.filters.historySearch;$('historyList').innerHTML=historyGames().map(g=>gameCard(g,true)).join('')||'<div class="empty">No games match these filters.</div>';updateCompareBtn()}
function renderCardBuilder(){const games=completed(state.games).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')),seasons=unique('seasonName'),type=$('cardTypeSelect').value;$('cardGameSelect').innerHTML=games.map(g=>`<option value="${g.id}">${fmtDate(g.date)} vs ${esc(g.opponent)}</option>`).join('')||'<option value="">No completed games</option>';$('cardSeasonSelect').innerHTML=seasons.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')||'<option value="">No seasons</option>';$('cardGameWrap').classList.toggle('hidden',type!=='game');$('cardSeasonWrap').classList.toggle('hidden',type!=='season')}
function updateCompareBtn(){const n=$$('[data-compare]:checked').length;$('compareBtn').disabled=n!==2;$('compareBtn').textContent=n===2?'Compare 2 games':'Compare selected'}
function renderSettings(){$('settingsPlayer').value=state.playerName;$('settingsSeason').value=state.seasonName;$('settingsLeague').value=state.leagueName;$('settingsTeam').value=state.teamName;$('themeSelect').value=state.settings.theme;$('hapticsToggle').checked=state.settings.haptics;$('wakeLockToggle').checked=state.settings.wakeLock;$('playTimeToggle').checked=state.settings.playTime}
function startGame(){const player=state.playerName.trim();if(!player){alert('Set the player name in Settings first.');return}const g={id:id(),playerName:player,opponent:$('opponentInput').value.trim(),date:$('gameDateInput').value,seasonName:$('gameSeasonInput').value.trim()||'Unassigned',leagueName:$('gameLeagueInput').value.trim()||'Unassigned',teamName:$('gameTeamInput').value.trim()||'Unassigned',notes:'',favorite:false,teamScore:'',opponentScore:'',periods:{Q1:basePeriod(),Q2:basePeriod(),Q3:basePeriod(),Q4:basePeriod()},activePeriod:'Q1',events:[],achievements:{},createdAt:Date.now(),endedAt:null,playTimeMs:0,isPlaying:false,playStartedAt:null};state.games.push(g);state.activeGameId=g.id;save();$('newGameDialog').close();setView('game')}
function endGame(){const g=activeGame();if(!g)return;saveFinalScore();if(g.teamScore==='')g.teamScore=totals(g).points;if(g.isPlaying){g.playTimeMs+=Date.now()-g.playStartedAt;g.isPlaying=false;g.playStartedAt=null}g.endedAt=Date.now();save();releaseWake();renderGame();showSummary(g)}
function showSummary(g){const t=totals(g),score=finalScoreText(g);$('summaryTitle').textContent=`vs ${g.opponent}`;$('summaryBadges').innerHTML=achievementBadges(g);$('summaryFinalScore').classList.toggle('hidden',!score);$('summaryFinalScore').innerHTML=score?`<h3>Final score</h3><p class="score-result">${esc(score)}${resultText(g)?` • ${resultText(g)}`:''}</p>`:'';$('summaryStats').innerHTML=statCard('PTS',t.points)+statCard('REB',t.rebounds)+statCard('AST',t.assists)+statCard('STL',t.steals)+statCard('BLK',t.blocks)+statCard('MIN',f1(t.minutes));$('summaryShooting').innerHTML=`<h3>Shooting</h3>${shootingCards(t)}`;$('summaryPeriods').innerHTML=`<table><thead><tr><th>Period</th><th>PTS</th><th>REB</th><th>AST</th><th>STL</th><th>BLK</th></tr></thead><tbody>${periodOrder(g).map(k=>{const p=g.periods[k];return`<tr><td>${k}</td><td>${periodPoints(p)}</td><td>${p.rebounds}</td><td>${p.assists}</td><td>${p.steals}</td><td>${p.blocks}</td></tr>`}).join('')}</tbody></table>`;$('summaryNotesWrap').classList.toggle('hidden',!g.notes.trim());$('summaryNotes').textContent=g.notes;$('summaryResume').classList.toggle('hidden',!g.endedAt);$('summaryDialog').showModal()}
function shareText(g){const t=totals(g),score=finalScoreText(g);return `HoopTrack — ${g.playerName}\nvs ${g.opponent} • ${fmtDate(g.date)}\n${g.seasonName} • ${g.leagueName} • ${g.teamName}${score?`\nFinal: ${score}${resultText(g)?` • ${resultText(g)}`:''}`:''}\n\nPTS ${t.points} | REB ${t.rebounds} | AST ${t.assists} | STL ${t.steals} | BLK ${t.blocks} | TO ${t.turnovers} | PF ${t.fouls}\nFG ${t.fgMade}/${t.fgAtt} (${fp(t.fgPct)}) | 3PT ${t.threeMade}/${t.threeAtt} (${fp(t.threePct)}) | FT ${t.ftMade}/${t.ftAtt} (${fp(t.ftPct)})\n${achievementList(g).map(x=>x[0]).join(' • ')}${g.notes?`\n\nNotes:\n${g.notes}`:''}`}
async function shareGame(g){const text=shareText(g);try{if(navigator.share)await navigator.share({title:`HoopTrack vs ${g.opponent}`,text});else{await navigator.clipboard.writeText(text);alert('Game summary copied.') }}catch{}}
function backup(){download(`hooptrack-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({...state,exportedAt:new Date().toISOString(),appVersion:VERSION},null,2),'application/json')}
function csv(){const rows=[['Date','Player','Season','League','Team','Opponent','Team Score','Opponent Score','Result','PTS','REB','AST','STL','BLK','TO','PF','FGM','FGA','FG%','3PM','3PA','3P%','FTM','FTA','FT%','Minutes','Favorite','Notes']];for(const g of completed(state.games)){const t=totals(g);rows.push([g.date,g.playerName,g.seasonName,g.leagueName,g.teamName,g.opponent,g.teamScore,g.opponentScore,resultText(g),t.points,t.rebounds,t.assists,t.steals,t.blocks,t.turnovers,t.fouls,t.fgMade,t.fgAtt,f1(t.fgPct),t.threeMade,t.threeAtt,f1(t.threePct),t.ftMade,t.ftAtt,f1(t.ftPct),f1(t.minutes),g.favorite?'Yes':'No',g.notes])}download('hooptrack-games.csv',rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),'text/csv')}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function restore(file){const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!Array.isArray(p.games))throw 0;if(!confirm(`Restore ${p.games.length} games? This replaces current HoopTrack data.`))return;state={...clone(initial),...p,settings:{...initial.settings,...p.settings},filters:{...initial.filters,...p.filters},games:p.games.map(normalizeGame)};save();applyTheme();renderAll();alert('HoopTrack backup restored.')}catch{alert('That file is not a valid HoopTrack backup.')}};r.readAsText(file)}
function compareSelected(){const ids=$$('[data-compare]:checked').map(x=>x.dataset.compare),gs=ids.map(x=>state.games.find(g=>g.id===x)).filter(Boolean);if(gs.length!==2)return;const metrics=[['Final','final'],['Result','result'],['PTS','points'],['REB','rebounds'],['AST','assists'],['STL','steals'],['BLK','blocks'],['TO','turnovers'],['FG%','fgPct'],['3PT%','threePct']];$('compareContent').innerHTML=`<table class="compare-table"><thead><tr><th>Stat</th>${gs.map(g=>`<th>vs ${esc(g.opponent)}<br><span class="muted small">${fmtDate(g.date)}</span></th>`).join('')}</tr></thead><tbody>${metrics.map(([l,k])=>`<tr><td>${l}</td>${gs.map(g=>`<td>${k==='final'?(finalScoreText(g)||'--'):k==='result'?(resultText(g)||'--'):k.includes('Pct')?fp(totals(g)[k]):totals(g)[k]}</td>`).join('')}</tr>`).join('')}</tbody></table>`;$('compareDialog').showModal()}
function loadImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=URL.createObjectURL(file)})}
function drawCover(ctx,img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),dw=img.width*s,dh=img.height*s;ctx.drawImage(img,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
function drawText(ctx,text,x,y,maxWidth,size,weight='800',color='#f8fafc',align='left'){ctx.font=`${weight} ${size}px Impact, Haettenschweiler, Arial Narrow, sans-serif`;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='alphabetic';let s=String(text??'');while(ctx.measureText(s).width>maxWidth&&size>18){size-=2;ctx.font=`${weight} ${size}px Impact, Haettenschweiler, Arial Narrow, sans-serif`}ctx.fillText(s,x,y)}
function statFilled(value){return value!==''&&value!=null&&Number(value)!==0}
function cardStats(){const type=$('cardTypeSelect').value;if(type==='game'){const g=state.games.find(x=>x.id===$('cardGameSelect').value);if(!g)return null;const t=totals(g);return {type:'GAME CARD',title:g.playerName||state.playerName||'Player',subtitle:`vs ${g.opponent} • ${fmtDate(g.date)}`,score:finalScoreText(g)||`${g.teamName||'Team'} vs ${g.opponent}`,stats:[['PTS',t.points],['REB',t.rebounds],['AST',t.assists],['STL',t.steals],['BLK',t.blocks]].filter(([,v])=>statFilled(v)),footer:`${g.seasonName} • ${g.leagueName}`}}const season=$('cardSeasonSelect').value,gs=scopedGames(season,'');const a=agg(gs);return {type:'SEASON CARD',title:state.playerName||'Player',subtitle:season||'All seasons',score:`${a.games.length} games`,stats:[['PPG',f1(a.avg('points'))],['RPG',f1(a.avg('rebounds'))],['APG',f1(a.avg('assists'))],['SPG',f1(a.avg('steals'))],['BPG',f1(a.avg('blocks'))]].filter(([,v])=>statFilled(v)),footer:`FG ${fp(a.fgPct)} • 3PT ${fp(a.threePct)} • FT ${fp(a.ftPct)}`}}
function generateCard(){const data=cardStats(),c=$('cardCanvas'),ctx=c.getContext('2d');if(!data){alert('Choose a completed game or season first.');return}ctx.clearRect(0,0,c.width,c.height);const W=c.width,H=c.height,rail=230;const grad=ctx.createLinearGradient(0,0,W,H);grad.addColorStop(0,'#f8fafc');grad.addColorStop(.52,'#dbe6f2');grad.addColorStop(1,'#101827');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);if(cardPhoto){drawCover(ctx,cardPhoto,0,0,W,H);ctx.fillStyle='rgba(248,250,252,.48)';ctx.fillRect(rail,0,W-rail,H);ctx.save();ctx.beginPath();ctx.rect(rail+42,72,W-rail-84,820);ctx.clip();drawCover(ctx,cardPhoto,rail+42,72,W-rail-84,820);ctx.restore()}ctx.fillStyle='rgba(8,18,32,.94)';ctx.fillRect(0,0,rail,H);let shade=ctx.createLinearGradient(rail,0,W,0);shade.addColorStop(0,'rgba(248,250,252,.9)');shade.addColorStop(.34,'rgba(248,250,252,.32)');shade.addColorStop(1,'rgba(8,18,32,.42)');ctx.fillStyle=shade;ctx.fillRect(rail,0,W-rail,H);shade=ctx.createLinearGradient(0,0,0,H);shade.addColorStop(0,'rgba(8,18,32,.48)');shade.addColorStop(.28,'rgba(8,18,32,0)');shade.addColorStop(.68,'rgba(8,18,32,0)');shade.addColorStop(1,'rgba(8,18,32,.56)');ctx.fillStyle=shade;ctx.fillRect(rail,0,W-rail,H);ctx.strokeStyle='#101827';ctx.lineWidth=10;ctx.strokeRect(34,34,W-68,H-68);ctx.save();ctx.translate(118,430);ctx.rotate(-Math.PI/2);drawText(ctx,data.type,0,0,610,78,'900','#f8fafc','center');ctx.restore();ctx.fillStyle='#ff7a1a';ctx.fillRect(58,126,142,12);drawText(ctx,'HOOPTRACK',70,1214,330,43,'900','#ff7a1a');drawText(ctx,'STAT LINE',70,1254,330,23,'800','#f8fafc');ctx.shadowColor='rgba(255,255,255,.7)';ctx.shadowBlur=12;drawText(ctx,data.title.toUpperCase(),W-70,118,620,48,'900','#0b1220','right');drawText(ctx,data.subtitle.toUpperCase(),W-70,170,620,30,'800','#1f2937','right');ctx.shadowBlur=0;ctx.fillStyle='rgba(248,250,252,.82)';ctx.fillRect(rail+42,560,W-rail-84,126);drawText(ctx,'SCORE',rail+72,604,220,26,'800','#334155');drawText(ctx,data.score.toUpperCase(),rail+72,664,W-rail-140,52,'900','#0b1220');const stats=data.stats.length?data.stats:[['PTS',0]],areaX=rail+72,areaW=W-rail-144,gap=Math.min(46,areaW/(stats.length*5)),r=Math.min(72,(areaW-gap*(stats.length-1))/(stats.length*2)),startX=areaX+r+(areaW-(stats.length*r*2+gap*(stats.length-1)))/2,y=1002;stats.forEach(([label,value],i)=>{const x=startX+i*(r*2+gap);ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle='rgba(248,250,252,.96)';ctx.fill();ctx.lineWidth=8;ctx.strokeStyle='#101827';ctx.stroke();drawText(ctx,value,x,y+8,r*1.45,Math.min(62,r*.86),'900','#101827','center');drawText(ctx,label,x,y+r*.67,r*1.35,23,'800','#101827','center')});ctx.fillStyle='rgba(248,250,252,.78)';ctx.fillRect(rail+42,1122,W-rail-84,72);drawText(ctx,data.footer.toUpperCase(),W/2+rail/2,1170,W-rail-144,32,'800','#101827','center');c.toBlob(b=>{cardBlob=b;$('downloadCardBtn').disabled=!b;$('shareCardBtn').disabled=!b},'image/png')}
function downloadCard(){if(!cardBlob)return;download(`hooptrack-card-${Date.now()}.png`,cardBlob,'image/png')}
async function shareCard(){if(!cardBlob)return;const file=new File([cardBlob],`hooptrack-card-${Date.now()}.png`,{type:'image/png'});try{if(navigator.canShare?.({files:[file]})&&navigator.share)await navigator.share({files:[file],title:'HoopTrack card'});else downloadCard()}catch{}}
function bind(){
$$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));$('goHistoryBtn').onclick=()=>setView('history');$('newGameBtn').onclick=()=>{if(!state.playerName){setView('settings');$('settingsPlayer').focus();return}$('opponentInput').value='';$('gameDateInput').value=new Date().toISOString().slice(0,10);$('gameSeasonInput').value=state.seasonName;$('gameLeagueInput').value=state.leagueName;$('gameTeamInput').value=state.teamName;$('newGameDialog').showModal()};$('cancelNewGame').onclick=()=>$('newGameDialog').close();$('newGameForm').addEventListener('submit',e=>{e.preventDefault();startGame()});
$('gameView').addEventListener('click',e=>{const s=e.target.closest('[data-stat]');if(s)logStat(s.dataset.stat);const p=e.target.closest('[data-period]');if(p){const g=activeGame();if(g&&!g.endedAt){g.activePeriod=p.dataset.period;save();renderGame()}}const de=e.target.closest('[data-delete-event]');if(de)deleteEvent(de.dataset.deleteEvent);if(e.target.id==='addOTBtn'){const g=activeGame(),n=periodOrder(g).filter(x=>x.startsWith('OT')).length+1,pk='OT'+n;ensurePeriod(g,pk);g.activePeriod=pk;save();renderGame()}});
$('teamScoreInput').addEventListener('input',()=>{$('finalScoreSaved').textContent='Unsaved'});$('opponentScoreInput').addEventListener('input',()=>{$('finalScoreSaved').textContent='Unsaved'});$('saveFinalScoreBtn').onclick=saveFinalScore;$('gameNotes').addEventListener('input',e=>{const g=activeGame();if(g&&!g.endedAt){g.notes=e.target.value;save();$('notesSaved').textContent='Saved'}});$('undoBtn').onclick=()=>{const g=activeGame();if(g?.events.length)deleteEvent(g.events.at(-1).id)};$('togglePlayBtn').onclick=togglePlaying;$('endGameBtn').onclick=endGame;$('resumeGameBtn').onclick=()=>{const g=activeGame();if(g){g.endedAt=null;save();renderGame();requestWake()}};$('favoriteBtn').onclick=()=>{const g=activeGame();if(g){g.favorite=!g.favorite;save();renderGame()}};
$('summaryDone').onclick=()=>{$('summaryDialog').close();setView('home')};$('closeSummary').onclick=()=>$('summaryDialog').close();$('summaryResume').onclick=()=>{const g=activeGame();if(g){g.endedAt=null;save();$('summaryDialog').close();renderGame();requestWake()}};$('summaryShare').onclick=()=>{const g=activeGame();if(g)shareGame(g)};$('rewardClose').onclick=()=>$('rewardDialog').close();$('closeCompare').onclick=()=>$('compareDialog').close();
$('profileForm').addEventListener('submit',e=>{e.preventDefault();state.playerName=$('settingsPlayer').value.trim();state.seasonName=$('settingsSeason').value.trim();state.leagueName=$('settingsLeague').value.trim();state.teamName=$('settingsTeam').value.trim();save();renderAll();alert('Profile saved.')});
$('themeSelect').onchange=e=>{state.settings.theme=e.target.value;save();applyTheme()};$('quickThemeBtn').onclick=()=>{state.settings.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';save();applyTheme()};$('hapticsToggle').onchange=e=>{state.settings.haptics=e.target.checked;save()};$('wakeLockToggle').onchange=e=>{state.settings.wakeLock=e.target.checked;save();e.target.checked?requestWake():releaseWake()};$('playTimeToggle').onchange=e=>{state.settings.playTime=e.target.checked;save();renderGame()};$('backupBtn').onclick=backup;$('csvBtn').onclick=csv;$('restoreInput').onchange=e=>e.target.files[0]&&restore(e.target.files[0]);
const filterMap={dashboardSeasonFilter:'dashboardSeason',dashboardLeagueFilter:'dashboardLeague',seasonFilter:'season',seasonLeagueFilter:'seasonLeague',historySeasonFilter:'historySeason',historyLeagueFilter:'historyLeague',historySort:'historySort'};for(const [el,k] of Object.entries(filterMap))$(el).onchange=e=>{state.filters[k]=e.target.value;save();renderAll()};$('favoritesOnly').onchange=e=>{state.filters.favoritesOnly=e.target.checked;save();renderHistory()};$('historySearch').oninput=e=>{state.filters.historySearch=e.target.value;save();renderHistory()};$('trendMetric').onchange=()=>renderHome();$('compareBtn').onclick=compareSelected;
$('cardTypeSelect').onchange=()=>renderCardBuilder();$('cardPhotoInput').onchange=async e=>{const file=e.target.files[0];if(file){cardPhoto=await loadImage(file);cardBlob=null;$('downloadCardBtn').disabled=true;$('shareCardBtn').disabled=true;generateCard()}};$('generateCardBtn').onclick=generateCard;$('downloadCardBtn').onclick=downloadCard;$('shareCardBtn').onclick=shareCard;
$('historyList').addEventListener('click',e=>{const v=e.target.closest('[data-view-game]'),sh=e.target.closest('[data-share-game]'),fav=e.target.closest('[data-favorite-game]'),del=e.target.closest('[data-delete-game]');if(v){state.activeGameId=v.dataset.viewGame;save();setView('game');const g=activeGame();if(g?.endedAt)showSummary(g)}if(sh){const g=state.games.find(x=>x.id===sh.dataset.shareGame);if(g)shareGame(g)}if(fav){const g=state.games.find(x=>x.id===fav.dataset.favoriteGame);if(g){g.favorite=!g.favorite;save();renderHistory()}}if(del){const g=state.games.find(x=>x.id===del.dataset.deleteGame);if(g&&confirm(`Delete game vs ${g.opponent}?`)){state.games=state.games.filter(x=>x.id!==g.id);if(state.activeGameId===g.id)state.activeGameId=null;save();renderAll()}}});$('historyList').addEventListener('change',e=>{if(e.target.matches('[data-compare]')){const checked=$$('[data-compare]:checked');if(checked.length>2)e.target.checked=false;updateCompareBtn()}});
$('recentGames').addEventListener('click',e=>{const v=e.target.closest('[data-view-game]'),sh=e.target.closest('[data-share-game]');if(v){state.activeGameId=v.dataset.viewGame;save();setView('game');const g=activeGame();if(g?.endedAt)showSummary(g)}if(sh){const g=state.games.find(x=>x.id===sh.dataset.shareGame);if(g)shareGame(g)}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&currentView==='game')requestWake()});matchMedia('(prefers-color-scheme: light)').addEventListener?.('change',()=>state.settings.theme==='system'&&applyTheme());
}
async function registerSW(){if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./sw.js',{scope:'./'})}catch(e){console.warn(e)}}
function init(){applyTheme();bind();renderAll();setView(state.activeGameId?'game':'home');timerHandle=setInterval(()=>{if(currentView==='game'&&activeGame()?.isPlaying)renderGame()},1000);registerSW()}
init();
})();
